### ISSUE TITLE
https://scratch.mit.edu/projects/187965857/

### ISSUE THREAD

**Issue by Vampire94937** [nathan/phosphorus#1009]
https://scratch.mit.edu/projects/187965857/
http://phosphorus.github.io/#187965857
Mozilla/5.0 (X11; CrOS x86_64 9901.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.97 Safari/537.36

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:28:8)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by Vampire94937** [comment]
thonks is fixd now

**Comment by randum145** [comment]
How did you fix it?
