### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Ryan12439** [nathan/phosphorus#1105]
http://scratch.mit.edu/projects/93037082
http://phosphorus.github.io/#93037082

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:19:8)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by Guiguiclash** [comment]
Idem for me...
