### ISSUE TITLE
Game of Clicks Beta

### ISSUE THREAD

**Issue by wafflezofwaffleness** [nathan/phosphorus#1140]
http://scratch.mit.edu/projects/210546649
http://phosphorus.github.io/#210546649

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:3:7)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by wafflezofwaffleness** [comment]
Stop all makes it crash.

**Comment by INFIN1TE** [comment]
As a part of Infinity Development, please join our new Discord server! We will slowly stop using the team chat and use the Discord server instead. Join now: https://discord.gg/CftRa8a

**Comment by wafflezofwaffleness** [comment]
My username on discord is [GD] Waffle, not my scratch username. But it is me. :)

**Comment by INFIN1TE** [comment]
Ok :)
