### ISSUE TITLE
Pokemon Fire Red ™ (GBA Scratch port) su Scratch

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#1247]
Each instruction is shown twice. Then, as soon as the game begins it crashes.

http://scratch.mit.edu/projects/166881028
http://phosphorus.github.io/#166881028

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:7)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by sfederici** [comment]
Each instruction is still shown twice. But the game now works and doesn't crash.
