### ISSUE TITLE
please help with this

### ISSUE THREAD

**Issue by pinzocl** [nathan/phosphorus#1260]
http://scratch.mit.edu/projects/228790085
http://phosphorus.github.io/#228790085

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:4:7)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by listopad** [comment]
just use my fixed version https://scratch2js.github.io/
