### ISSUE TITLE
drawing game sur Scratch

### ISSUE THREAD

**Issue by Youssef129** [nathan/phosphorus#1264]
http://scratch.mit.edu/projects/229756539
http://phosphorus.github.io/#229756539

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:29)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by Youssef129** [comment]
hello
