### ISSUE TITLE
Flappy Cöpcüler Krali auf Scratch

### ISSUE THREAD

**Issue by Hgegin** [nathan/phosphorus#1300]
http://scratch.mit.edu/projects/238052589
http://phosphorus.github.io/#238052589

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:34)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by Hgegin** [comment]
Help me please
