### ISSUE TITLE
Project: Loon LTE Beta 10.5 Mobile

### ISSUE THREAD

**Issue by Gamertube1238** [nathan/phosphorus#1301]
http://scratch.mit.edu/projects/237989526
http://phosphorus.github.io/#237989526

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:7)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by Gamertube1238** [comment]
what the ............................................................
