### ISSUE TITLE
Ping pong

### ISSUE THREAD

**Issue by Afsal102** [nathan/phosphorus#1302]
http://scratch.mit.edu/projects/238523134
http://phosphorus.github.io/#238523134

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:7)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by joshdragon04** [comment]
im getting that too
