### ISSUE TITLE
Geo.test

### ISSUE THREAD

**Issue by joshdragon04** [nathan/phosphorus#1303]
http://scratch.mit.edu/projects/228823295
http://phosphorus.github.io/#228823295

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:31)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by joshdragon04** [comment]
this is happening to me everytime i load a project :/
