### ISSUE TITLE
Gletscherrennen-ws-App auf Scratch

### ISSUE THREAD

**Issue by ruebenberg** [nathan/phosphorus#1345]
http://scratch.mit.edu/projects/138190499
http://phosphorus.github.io/#138190499

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:9)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by ruebenberg** [comment]
http://phosphorus.github.io/#138190499
