### ISSUE TITLE
Fortnite Battle Royale

### ISSUE THREAD

**Issue by crohn64** [nathan/phosphorus#1404]
http://scratch.mit.edu/projects/268919235
http://phosphorus.github.io/#268919235

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:4:8)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by callowaysutton** [comment]
Cannot replicate the error.
It seems to work fine on Edge Windows 10 November Update.

I think this issue is closed
