### ISSUE TITLE
flappy bird (türk yapımı) Scratch

### ISSUE THREAD

**Issue by muradiyaman** [nathan/phosphorus#1419]
http://scratch.mit.edu/projects/66344802
http://phosphorus.github.io/#66344802

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:38)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by muradiyaman** [comment]
http://phosphorus.github.io/#66344802

**Comment by callowaysutton** [comment]
Cannot repeat the error, what browser was being used?
Edge Windows 10 November Update.
