### ISSUE TITLE
Prueba

### ISSUE THREAD

**Issue by RubioMarta** [nathan/phosphorus#1504]
http://scratch.mit.edu/projects/286940604
http://phosphorus.github.io/#286940604

```
Error: HTTP 404: 
    at XMLHttpRequest.xhr.onload (https://phosphorus.github.io/phosphorus.js:224:23)
```

**Comment by RubioMarta** [comment]
> http://scratch.mit.edu/projects/286940604
> http://phosphorus.github.io/#286940604
> 
> ```
> Error: HTTP 404: 
>     at XMLHttpRequest.xhr.onload (https://phosphorus.github.io/phosphorus.js:224:23)
> ```
