### ISSUE TITLE
Bitmap waffle

### ISSUE THREAD

**Issue by armando12323** [nathan/phosphorus#1538]
http://scratch.mit.edu/projects/98607394
http://phosphorus.github.io/#98607394

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:8)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by armando12323** [comment]
No me gusta este error
