### ISSUE TITLE
maze game

### ISSUE THREAD

**Issue by loovfdfc** [nathan/phosphorus#1755]
http://scratch.mit.edu/projects/319971367
http://phosphorus.github.io/#319971367

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:22:7)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by loovfdfc** [comment]
gbbft
