### ISSUE TITLE
https://scratch.mit.edu/projects/349734351/ #1962

### ISSUE THREAD

**Issue by tabsamir** [nathan/phosphorus#1963]
http://scratch.mit.edu/projects/349734351
http://phosphorus.github.io/#349734351

```
Error: HTTP 404: 
    at XMLHttpRequest.xhr.onload (https://phosphorus.github.io/phosphorus.js:224:23)
```

**Comment by tabsamir** [comment]
at XMLHttpRequest.xhr.onload (https://phosphorus.github.io/phosphorus.js:224:23)
