### ISSUE TITLE
(Haven't set a name for my project.. ;) )

### ISSUE THREAD

**Issue by liam4** [nathan/phosphorus#374]
http://scratch.mit.edu/projects/56841090
http://phosphorus.github.io/#56841090

```
TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': float parameter 3 is non-finite.
    at TypeError (native)
    at Sprite.touching (http://phosphorus.github.io/phosphorus.js:1497:37)
    at eval (eval at <anonymous> (http://phosphorus.github.io/phosphorus.js:3878:19), <anonymous>:18:7)
    at P.runtime.P.Stage.step (http://phosphorus.github.io/phosphorus.js:3802:15)
```

**Comment by trumank** [comment]
This is fixed by #369
