### ISSUE TITLE
Welcome to PLATFORM3D

### ISSUE THREAD

**Issue by DA-REDFLAME** [nathan/phosphorus#397]
Ah, i see the bug. Add an absolute value to your pen javascript thing so that it works properly.
http://scratch.mit.edu/projects/64076932
http://phosphorus.github.io/#64076932

```
Error: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-0.347785) is negative.
    at Error (native)
    at Sprite.dotPen (http://phosphorus.github.io/phosphorus.js:1403:13)
    at eval (eval at <anonymous> (http://phosphorus.github.io/phosphorus.js:3876:19), <anonymous>:7:3)
    at P.runtime.P.Stage.step (http://phosphorus.github.io/phosphorus.js:3800:15)
```

**Comment by nathan** [comment]
Fixed now.
