### ISSUE TITLE
Color Sensing on Size 0 crashes

### ISSUE THREAD

**Issue by DevanWolf** [nathan/phosphorus#491]
Sensing color sprite is touching red when the sprite's size is 0 crashes Phosphorus.

http://phosphorus.github.io#84651422

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Error (native)
    at Sprite.touchingColor (http://phosphorus.github.io/phosphorus.js:1520:33)
    at eval (eval at <anonymous> (http://phosphorus.github.io/phosphorus.js:3876:19), <anonymous>:4:16)
    at P.runtime.P.Stage.step (http://phosphorus.github.io/phosphorus.js:3800:15)
```

**Comment by htmlgames** [comment]
Check length in Sprite.prototype.touching and Sprite.prototype.touchingColor
var length = (right - left) * (top - bottom) * 4; // moved this line up from below.
        if (length) {
        var data = collisionContext.getImageData(0, 0, right - left, top - bottom).data;
.....
