### ISSUE TITLE
when hell is full demo

### ISSUE THREAD

**Issue by deadhobos** [nathan/phosphorus#502]
http://scratch.mit.edu/projects/86933840
http://phosphorus.github.io/#86933840

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Error (native)
    at Sprite.touchingColor (http://phosphorus.github.io/phosphorus.js:1520:33)
    at eval (eval at <anonymous> (http://phosphorus.github.io/phosphorus.js:3878:19), <anonymous>:8:8)
    at P.runtime.P.Stage.step (http://phosphorus.github.io/phosphorus.js:3802:15)
```

**Comment by DevanWolf** [comment]
Same happened on #491 or may be a duplicate.
