### ISSUE TITLE
Super Square

### ISSUE THREAD

**Issue by rwahdan** [nathan/phosphorus#843]
http://scratch.mit.edu/projects/167583082
http://phosphorus.github.io/#167583082

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:41)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by rwahdan** [comment]
I am trying to make scratch to work with apk
