### ISSUE TITLE
Climberman

### ISSUE THREAD

**Issue by HTML144** [nathan/phosphorus#885]
http://scratch.mit.edu/projects/171307849
http://phosphorus.github.io/#171307849

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:32:7)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by ateesdalejr** [comment]
Looks like a bug with collision...
