### ISSUE TITLE
Pixel infection not working

### ISSUE THREAD

**Issue by pkaliny** [nathan/phosphorus#888]
http://scratch.mit.edu/projects/164753789
http://phosphorus.github.io/#164753789

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Sprite.touchingColor (https://phosphorus.github.io/phosphorus.js:1670:33)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:30:8)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by RainingCode7** [comment]
Same thing happening here!
