### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SlimTeam** [nathan/phosphorus#892]
http://scratch.mit.edu/projects/172477541
http://phosphorus.github.io/#172477541

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:7)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by Tolfaroxe** [comment]
https://phosphorus.github.io/#276680899
Voilà, je suis nouveau mais rien ne marche malheureusement...
