### ISSUE TITLE
phosphorus test

### ISSUE THREAD

**Issue by HAZZAZLAR** [nathan/phosphorus#973]
http://scratch.mit.edu/projects/182276507
http://phosphorus.github.io/#182276507

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:8)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

An error that just occurred when I died in my game.

**Comment by tantalate** [comment]
same error
