### ISSUE TITLE
It didn't work

### ISSUE THREAD

**Issue by Sir-Cool** [nathan/phosphorus#978]
I don't know what the error Dan's, but here's the report anyway, just in case you might find it helpful.

http://scratch.mit.edu/projects/128656639
http://phosphorus.github.io/#128656639

```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Sprite.touching (https://phosphorus.github.io/phosphorus.js:1643:37)
    at eval (eval at scopedEval (https://phosphorus.github.io/phosphorus.js:4014:14), <anonymous>:2:9)
    at Stage.P.runtime.P.Stage.step (https://phosphorus.github.io/phosphorus.js:3938:15)
```

**Comment by Sir-Cool** [comment]
I just tried it on my computer and it worked. The error only appeared on a mobile device. It was an android and I was viewing phosphorus on chrome.
